<h1 style="color:red;">Lab 1</h1>

*Date: Thursday 7/3/2024*

<h2>Lab Objectives:</h2>
<ol>
    <li>Introduction to notebooks</li>
    <li>A glimpse of Numpy</li>
</ol>
<i>By Ahmed Qarqaz</i>




# Intro to Notebooks
Notebooks  allows you to write and execute code <u>interactively</u>, view the results immediately, and add explanatory text or visualizations alongside the code.<br>
A normal Python script, on the other hand, is a plain text file containing Python code. And the codelines within the file are executed all at once.<br>

There are two types of cells in notebooks:
<ol>
    <li>Code cells: used for writing python code</li>
    <li>Markdown cells: primarily used for annotating and structuring the notebooks</li>
</ol>

## Coding in Notebooks
Code cells are where you write and run your Python code. Think of these blocks as small scripts that you can run on their own, in any order.<br>
Let's start with the first thing any programmer does: introducing yourself to the world:

In [1]:
print('Hello World')

Hello World


To run the code **only in this cell**, you can use the keyboard `ctrl-Enter`  when you've clicked into it or hit the play button on the left side of the cell.<br>
Once this code is run, you'll see a number in the top left corner of the block. The software will automatically keep track of how many cells have been run and indicates what run number that cell has now done. For example, if you've haven't run any cells in this notebook yet, this number will show `[1]`. If three cells have run before it, then the number will show `[4]`. Once the cell is done running, any output (print statments or even images!) is placed below it.
Try a few of the cells below:

In [2]:
# Cells will only output the last return value unless you tell it to print things otherwise

5 + 5 # This won't show up since it's not the last returned value

print('Hello World, again...') # This shows up since it's a command

4 + 4 # This also shows up since it's the last returned value

Hello World, again...


8

In addition to working within specific cells, you can pass values or objects from cell to cell

In [3]:
# Let's store a value usinga variable
a = 5

You'll notice that there is no output since "5" is being stored in "a". We can now reference a later **after** the code has been run before.

In [4]:
print(a + a) # Let's add the variable to itself!

10


In [5]:
# Here's is an example of an error that occurs when referencing objects
# or variables from cells that haven't been run yet

print(b) # B comes from below, but hasn't been run yet.

NameError: name 'b' is not defined

In [6]:
b = "Welcome to AI ;)"
print(b) # Now that it's defined, there will be no error

Welcome to AI ;)


Comments can be used to add written context or reminders in the middle of your Python code. There are two types of comments that you can use.
<ol>
    <li> # Indicates inline comments that start at that character and extend for the remainder of the line.</li>
    <li> Multi-line comments are indicated using ''' (see examples below).</li>
</ol>




In [7]:
'''
This is an example of a multi-line comment

Anything within the two sets of indicators will not be run
'''

a = 5 # this is a single line comment. Anything after # will not be run

## Markdown Cells (text cells)
Text cells are where you will want to write comments, descriptions, and other information that isn't code.

Text cells have two states, a <u>viewing state</u> and an <u>editing state</u>. When in the viewing state, the text is rendered like any other page you'll find on the internet (with italics, bolded text, underlines, etc.) You can quickly go to the edit state by double-clicking the cell. When you do this, you should see a similar interface to the one below:

Adding and formating text in these text cells use a plain text syntax style called **Markdown**. By adding different symbols to your text, the software will automatically format your text once you're done editing. To finish editing, click anywhere outside of the cell or use the keyboard shortcut, `Shift-Enter` or `ctrl-Enter`.

<big>Below are the basic items you'll need when adding text.</big>

**Bold Text**: `**Text**`  

*Italics*: `*Text*`  

**Images**: `![image description](URL)`  

**Headers**: `# Header 1`, `## Header 2`

**Unordered Lists**:
```
- Item 1
- Item 2
- Item 3
```

**Ordered Lists**:
```
1. Item 1
2. Item 2
3. Item 3
```

<big>Or, if you are familiar with HTML elements you can do the following:</big>

<strong>Bold Text</strong>: `<strong>Text</strong>`

<em>Italics</em>: `<em>Text</em>`

Images: `<img src="URL" alt="image description">`

Headers: `<h1>Header 1</h1>`, `<h2>Header 2</h2>`

Unordered Lists:

**Unordered Lists**:
```
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ul>
```

**Ordered Lists**:
```
<ol>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ol>
```

# Managing your Libraries

In [ ]:
"""
whenever you are starting a new project, It is good practice to make sure
that your development environment has all the correct APIs/packages you need as
well as the exact versions you need.

Note: you don't need to do this everytime if you are operating on a local
machine. This is needed when using cloud compute.
"""
!pip install numpy==1.25.2

In [2]:
# adding a library into your code
import numpy

In [3]:
# Checking the version of your libraries
print(numpy.__version__)

1.21.5


Some libraries come pre-installed with python 3.0 called "*Bulit-in Modules*".<br>
For example, `random` `math` and `os` are all built-in modules.

# Numpy
short for "Numerical Python" is a library numerical computing that provides support for arrays, matrices, and mathematical functions.

<h2>why ?</h2>
<ol>
    <li>
        <u>Efficiency</u>: arrays are implemented in C, which makes them faster and more memory efficient than Python lists for numerical operations.
    </li>
    <li>
        <u>Convenience</u>: provides a wide range of mathematical functions and operations that are optimized for arrays, making it easy to perform complex calculations with minimal code.
    </li>
    <li>
        Integration with other Libraries: NumPy is the foundation of many other scientific computing libraries in Python, such as SciPy, Pandas, Matplotlib, and scikit-learn.
    </li>
</ol>









## Simplest and most important operation (matrix multiplication)

In [3]:
# Lets define two matrices
x = [[1,2,3],
     [4,5,6],
     [7,8,9]]

y = [[1,2,3],
     [4,5,6],
     [7,8,9]]

# Initializing an empty list
z = [3*[0],
     3*[0],
     3*[0]]

# perform matrix addition
for i in range(len(z)):
    for j in range(len(z[i])):
        z[i][j] = x[i][j] + y[i][j]

for row in z:
    print(row)

[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


In [1]:
x = [[1,2,3],
     [4,5,6],
     [7,8,9]]

y = [[1,2,3],
     [4,5,6],
     [7,8,9]]

z = [3*[0],
     3*[0],
     3*[0]]

# Perform matrix multiplication
for i in range(len(x)):
    for j in range(len(y[0])):
        for k in range(len(y)):
            z[i][j] += x[i][k] * y[k][j]

for row in z:
    print(row)

[30, 36, 42]
[66, 81, 96]
[102, 126, 150]


In [5]:
import numpy as np

In [7]:
x = [[1,2,3],
     [4,5,6],
     [7,8,9]]

y = [[1,2,3],
     [4,5,6],
     [7,8,9]]

z = np.matmul(x,y)
print(z)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [10]:
z

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

<big>numpy stores the data in the form of arrays. Arrays are composed of elements of the same data type unlike lists which store multiple data types.</big>

## Initializing arrays

In [25]:
"""
It is very useful to initialize arrays given the number of rows and columns.
numpy allows us to do that using these functions:
    - np.zeros(row, col) --> array full of zeros
    - np.ones(row, col) --> array full ones.

we can also use the parameter 'dtype' to specify the data type we wish to work
with.
"""

rows = 3
columns = 4
shape = (rows, columns)
new_array = np.zeros(shape, dtype=int)
new_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
"""
sometimes it is useful to initialize an array with a random set of numbers
between 0 and 1:
    - np.random.rand(d1, d2, ....)
"""
rows = 3
columns = 4
new_array = np.random.rand(rows, columns)
new_array

array([[0.03293293, 0.67084533, 0.76856936, 0.25156969],
       [0.69456299, 0.24398181, 0.20365162, 0.16544974],
       [0.04689741, 0.90397703, 0.33625121, 0.92391267]])

In [29]:
"""
we can also generate a random set of integer numbers using:
    - np.random.randint(low, high, size)
"""
rows = 3
columns = 4
shape = (rows, columns)
new_array = np.random.randint(low=1, high=5, size=shape)
new_array

array([[3, 3, 2, 1],
       [1, 4, 1, 3],
       [4, 1, 4, 2]])

In [32]:
new_array

array([[3, 3, 2, 1],
       [1, 4, 1, 3],
       [4, 1, 4, 2]])

## Norms
calculating the norm of vectors is one of the most important calculations in
data science and machine learning.

In numpy, we accomplish that using the `numpy.linalg` module

In [37]:
"""
By default, the function uses L2-norm (also known as the 'Frobenius norm').
to specify the norm, we use the 'ord' parameter.
"""
x = np.array([1,2,3,4])
norm = np.linalg.norm(x, ord=2)
print(norm)

5.477225575051661


In [52]:
"""
We can also caluclate the norm for multiple vectors
"""
x = np.random.randint(low=1, high=5, size=(3,4))
print(f"matrix:\n{x}\n")
norm = np.linalg.norm(x, ord=2, axis=0)
print(f"norms: {norm}")

matrix:
[[1 1 2 4]
 [1 3 3 1]
 [3 4 4 3]]

norms: [3.31662479 5.09901951 5.38516481 5.09901951]


## Reshaping Arrays
It is often very important to reshape how the data is structred in matrices.
For example, when doing a transpose.

In [53]:
x = np.random.randint(low=1, high=5, size=(3,4))
x_transposed = x.T
print(f"Original matrix:\n{x}\n")
print(f"Transposed matrix:\n{x_transposed}\n")

Original matrix:
[[3 2 4 4]
 [4 4 1 4]
 [3 1 1 4]]

Transposed matrix:
[[3 4 3]
 [2 4 1]
 [4 1 1]
 [4 4 4]]



In [57]:
"""
another way to do it:
"""
x_reshaped = x.reshape(4,3)
print(f"Result:\n{x_transposed}\n")

Result:
[[3 4 3]
 [2 4 1]
 [4 1 1]
 [4 4 4]]



## Starting with our first dataset

We will be using the <a href="https://www.kaggle.com/competitions/titanic/overview">Titanic dataset</a> in this lab. <br>
The titanic dataset is a well known educational resource for machine learning beginners.
Steps to install the titanic dataset:
<ol>
    <li>Click on <a href="https://www.kaggle.com/competitions/titanic/data">this</a> link to install the titanic dataset.</li>
    <li>Scroll down until you see the `download all` button on the right bar and click it.</li>
    <li>Unzip the downloaded folder and place the contents in a desired folder.</li>
</ol>

In [5]:
# common practice to import pandas and label it 'pd'
import pandas as pd

WE first must obtain a 'path' to direct our program to the directory of our data.
Generally speaking, there are two types of paths:
<ol>
    <li>Absolute paths: paths that usually start from the 'root' directory of the OS.<br>
        In Windows, the root can be usually called `C` referring to the `C-drive`.<br>
        In Linux, its called the `root`.<br>
    </li>
    <li>Relative paths: a path to a directory that is relative (from the perspective) of the current path.
    </li>
</ol>

Pandas gives us the ability to load our data into the program using many mehtods, the most popular one is called `pandas.read_csv()`<br>
CSV is short for "Comma-separated Values" and is the format by which many tabular data files are stored as.<br>
In CSV files, the values of a column are seperated by a single comma (`,`) for one row.<br>
And rows are usually seperated by a "new-line" symbol (`\n`).

In [93]:
"""
The default value for the 'sep' parameter is ",".
Another possible values are "\t" for tab-seperated values.
"""
PATH = "../Datasets/train.csv"
my_dataset = pd.read_csv(PATH, sep=",")

In [28]:
my_dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

## Getting a first look at our dataset.

In [23]:
# pandas.DataFrame.info() function is useful for getting a first initial look at the columns of our dataset.
my_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [25]:
# DataFrame.describe() is very useful for obtaining the five-number-summary and 
# other standard statistics for columns of the dataset.
my_dataset.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [33]:
# Return a slice of the dataframe that contains the first x rows
my_dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [30]:
# Return a slice of the dataframe that contains the last x rows
my_dataset.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

## Taking a closer look at the columns
It is sometimes useful to see the nature of the values of a feature (column).

The `.unique()` method allows us to see all the unique values of a column.<br>
This is useful for when we want to analyze a <span style="color:red;">categorical<span> feature. <br>

In [60]:
my_dataset['Pclass'].unique()

array([3, 1, 2], dtype=int64)

The `.value_counts()` method allows us to see all the unique values of a categorical feature AND their occurrence in the dataset.<br>

In [61]:
my_dataset['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

## Indexing and Selection
We will encounter many cases in our projects where selecting samples (rows) with specific features (column values) would be necessary

In [38]:
# The most basic and straight forward way to access a value in the dataframe
my_dataset['Pclass'][0]

3

In [45]:
# to retrieve an entire row we use the .iloc method.
# We can also use this method to retrieve 'slices' of the dataframe
my_dataset.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

<big><i>We can generate a <span style="color:red;">boolean list</span> whos values are based on the values within the dataset</i></big>

In [46]:
result = my_dataset['Survived'] == 0

In [49]:
result

0       True
1      False
2      False
3      False
4       True
       ...  
886     True
887    False
888     True
889    False
890     True
Name: Survived, Length: 891, dtype: bool

<big><i>And now, we can use the boolean list to retrieve a slice of the dataframe using <code>.loc</code> method</i></big>

In [59]:
# generate a slice of the df that contains all the passengers that didn't survive.
my_dataset.loc[my_dataset['Survived'] == 0]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
6              7         0       1                   McCarthy, Mr. Timothy J   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch           Ticket     Fare Cabin Embarked  
0      male  22.0      1      0        A/5 21171   7.2500   NaN        S  
4      male  35.0      0      0           373450   8.0500   NaN        S  
5      male   NaN      0      0           330877   8.4583   NaN        Q  
6      male  54.0      0      0            17463  51.8625   E46        S  
7      male   2.0      3      1           349909  21.0750   NaN        S  
..      ...   ...    ...    ...              ...      ...   ...      ...  
884    male  25.0      0      0  SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5           382652  29.1250   NaN        Q  
886    male  27.0      0      0           211536  13.0000   NaN        S  
888  female   NaN      1      2       W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0           370376   7.7500   NaN        Q  

[549 rows x 12 columns]

In [54]:
# generate a slice of the df that contains all the passengers that are 10+ years old.
my_dataset.loc[my_dataset['Age'] >= 10]

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
885      5            382652  29.1250   NaN        Q  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[652 rows x 12 columns]

<big><i>We can also set multiple conditions</i></big><br>
Reminder: the `and`/`or` operations in python are represented as `&`/`|` respectively

In [58]:
# generate a slice of the df that contains all the passengers that are 10+ years old who didn't survive
conditions = (my_dataset['Age'] <= 10) & (my_dataset['Survived'] == 0)
my_dataset.loc[conditions]

PassengerId  Survived  Pclass                                     Name  \
7              8         0       3           Palsson, Master. Gosta Leonard   
16            17         0       3                     Rice, Master. Eugene   
24            25         0       3            Palsson, Miss. Torborg Danira   
50            51         0       3               Panula, Master. Juha Niilo   
63            64         0       3                    Skoog, Master. Harald   
119          120         0       3        Andersson, Miss. Ellis Anna Maria   
147          148         0       3         Ford, Miss. Robina Maggie "Ruby"   
164          165         0       3             Panula, Master. Eino Viljami   
171          172         0       3                     Rice, Master. Arthur   
182          183         0       3    Asplund, Master. Clarence Gustaf Hugo   
205          206         0       3               Strom, Miss. Telma Matilda   
278          279         0       3                       Rice, Master. Eric   
297          298         0       1             Allison, Miss. Helen Loraine   
374          375         0       3               Palsson, Miss. Stina Viola   
386          387         0       3          Goodwin, Master. Sidney Leonard   
419          420         0       3                Van Impe, Miss. Catharina   
480          481         0       3           Goodwin, Master. Harold Victor   
541          542         0       3     Andersson, Miss. Ingeborg Constanzia   
634          635         0       3                       Skoog, Miss. Mabel   
642          643         0       3            Skoog, Miss. Margit Elizabeth   
787          788         0       3                Rice, Master. George Hugh   
813          814         0       3       Andersson, Miss. Ebba Iris Alfrida   
819          820         0       3             Skoog, Master. Karl Thorsten   
824          825         0       3             Panula, Master. Urho Abraham   
850          851         0       3  Andersson, Master. Sigvard Harald Elias   
852          853         0       3                  Boulos, Miss. Nourelain   

        Sex   Age  SibSp  Parch      Ticket      Fare    Cabin Embarked  
7      male   2.0      3      1      349909   21.0750      NaN        S  
16     male   2.0      4      1      382652   29.1250      NaN        Q  
24   female   8.0      3      1      349909   21.0750      NaN        S  
50     male   7.0      4      1     3101295   39.6875      NaN        S  
63     male   4.0      3      2      347088   27.9000      NaN        S  
119  female   2.0      4      2      347082   31.2750      NaN        S  
147  female   9.0      2      2  W./C. 6608   34.3750      NaN        S  
164    male   1.0      4      1     3101295   39.6875      NaN        S  
171    male   4.0      4      1      382652   29.1250      NaN        Q  
182    male   9.0      4      2      347077   31.3875      NaN        S  
205  female   2.0      0      1      347054   10.4625       G6        S  
278    male   7.0      4      1      382652   29.1250      NaN        Q  
297  female   2.0      1      2      113781  151.5500  C22 C26        S  
374  female   3.0      3      1      349909   21.0750      NaN        S  
386    male   1.0      5      2     CA 2144   46.9000      NaN        S  
419  female  10.0      0      2      345773   24.1500      NaN        S  
480    male   9.0      5      2     CA 2144   46.9000      NaN        S  
541  female   9.0      4      2      347082   31.2750      NaN        S  
634  female   9.0      3      2      347088   27.9000      NaN        S  
642  female   2.0      3      2      347088   27.9000      NaN        S  
787    male   8.0      4      1      382652   29.1250      NaN        Q  
813  female   6.0      4      2      347082   31.2750      NaN        S  
819    male  10.0      3      2      347088   27.9000      NaN        S  
824    male   2.0      4      1     3101295   39.6875      NaN        S  
850    male   4.0    

## Preprocessing the Dataset
Preprocessing the dataset is one of the core steps taken during the development of almost all Mahcine Learning projects.<br>
Most dataset would not be ready for analysis/training machine learning algorithms. <br>
Therefore, it is necessary that we run our dataset through a preprocessing pipeline that modifies the values in the dataset according to a rule. <br>

### Example #1
<big>There are many reasons for preprocessing the values of a dataset, One of the most common ones is <span style="color:red;"><b><u>Encoding Categorical Values<u><b></span></big>

In [62]:
def map_gender(x):
    if x == "male":
        return 0
    elif x == "female":
        return 1

# we use the pandas.series.apply() method to apply a valid preprocessing function to a specified dataset column
my_dataset['Sex'] = my_dataset['Sex'].apply(map_gender)

In [63]:
my_dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
2                               Heikkinen, Miss. Laina    1  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
4                             Allen, Mr. William Henry    0  35.0      0   
..                                                 ...  ...   ...    ...   
886                              Montvila, Rev. Juozas    0  27.0      0   
887                       Graham, Miss. Margaret Edith    1  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"    1   NaN      1   
889                              Behr, Mr. Karl Howell    0  26.0      0   
890                                Dooley, Mr. Patrick    0  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

### Example #2
<big>Another common preprocessing step is called <span style="color:red;"><b><u>Discretization<u><b></span> (Also known as Binning)</big> <br>
It is the process of turning a numerical continuous feature into a categorical feature.

In [66]:
def map_ages(x):
    if (x < 10):
        return 0
    elif (x >= 10) & (x<20):
        return 1
    else:
        return 2        

my_dataset['Age'] = my_dataset['Age'].apply(map_ages)

In [67]:
my_dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex  Age  SibSp  \
0                              Braund, Mr. Owen Harris    0    0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1    0      1   
2                               Heikkinen, Miss. Laina    1    0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1    0      1   
4                             Allen, Mr. William Henry    0    0      0   
..                                                 ...  ...  ...    ...   
886                              Montvila, Rev. Juozas    0    0      0   
887                       Graham, Miss. Margaret Edith    1    0      0   
888           Johnston, Miss. Catherine Helen "Carrie"    1    2      1   
889                              Behr, Mr. Karl Howell    0    0      0   
890                                Dooley, Mr. Patrick    0    0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

### Example #3
<big>
    We may sometimes want to get rid of unnecessary features (columns) or troublesome rows in our datasets.<br>
    We do this using the <code>pandas.DataFrame.drop()</code> method <br>
    The following is useful for when we want to perform two common preprocessing techniques called:<br>
        <span style="color:red;"><b><u>Feature Selection<u><b></span> & <span style="color:red;"><b><u>Outlier Detection<u><b></span>
</big>

In [68]:
my_dataset.drop(columns=['PassengerId'])

Survived  Pclass                                               Name  Sex  \
0           0       3                            Braund, Mr. Owen Harris    0   
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1   
2           1       3                             Heikkinen, Miss. Laina    1   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1   
4           0       3                           Allen, Mr. William Henry    0   
..        ...     ...                                                ...  ...   
886         0       2                              Montvila, Rev. Juozas    0   
887         1       1                       Graham, Miss. Margaret Edith    1   
888         0       3           Johnston, Miss. Catherine Helen "Carrie"    1   
889         1       1                              Behr, Mr. Karl Howell    0   
890         0       3                                Dooley, Mr. Patrick    0   

     Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      0      1      0         A/5 21171   7.2500   NaN        S  
1      0      1      0          PC 17599  71.2833   C85        C  
2      0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3      0      1      0            113803  53.1000  C123        S  
4      0      0      0            373450   8.0500   NaN        S  
..   ...    ...    ...               ...      ...   ...      ...  
886    0      0      0            211536  13.0000   NaN        S  
887    0      0      0            112053  30.0000   B42        S  
888    2      1      2        W./C. 6607  23.4500   NaN        S  
889    0      0      0            111369  30.0000  C148        C  
890    0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [69]:
my_dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex  Age  SibSp  \
0                              Braund, Mr. Owen Harris    0    0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1    0      1   
2                               Heikkinen, Miss. Laina    1    0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1    0      1   
4                             Allen, Mr. William Henry    0    0      0   
..                                                 ...  ...  ...    ...   
886                              Montvila, Rev. Juozas    0    0      0   
887                       Graham, Miss. Margaret Edith    1    0      0   
888           Johnston, Miss. Catherine Helen "Carrie"    1    2      1   
889                              Behr, Mr. Karl Howell    0    0      0   
890                                Dooley, Mr. Patrick    0    0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

<big>As a safety mechanism, pandas doesn't overwrite the original form/values of any `pandas.DataFrame` object unless excplicitly programmed to do so.</big>

In [78]:
# to execute the desired drop effectively, we need to do the following
my_dataset = my_dataset.drop(columns=['PassengerId'])

In [79]:
my_dataset

Survived  Pclass                                               Name  \
0           0       3                            Braund, Mr. Owen Harris   
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2           1       3                             Heikkinen, Miss. Laina   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4           0       3                           Allen, Mr. William Henry   
..        ...     ...                                                ...   
886         0       2                              Montvila, Rev. Juozas   
887         1       1                       Graham, Miss. Margaret Edith   
888         0       3           Johnston, Miss. Catherine Helen "Carrie"   
889         1       1                              Behr, Mr. Karl Howell   
890         0       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [82]:
# another way is to set the drop() method to do the operation 'inplace'
my_dataset.drop(columns=['PassengerId'], inplace=True)

KeyError: "['PassengerId'] not found in axis"

<big>What if we decided to remove specific samples (rows) based on their features (columns) ?</big>

In [91]:
df2 = my_dataset.loc[my_dataset['Age']<10] # get all the samples with Age less than 10
indexes_to_drop = df2.index.tolist() # get indexes of all the samples we want to drop
my_dataset.drop(indexes_to_drop, inplace=True) # drop the samples with the given index list
my_dataset.reset_index(inplace=True, drop=True) # reset the indexes

In [92]:
my_dataset

level_0  index  Survived  Pclass  \
0          0      0         0       3   
1          1      1         1       1   
2          2      2         1       3   
3          3      3         1       1   
4          4      4         0       3   
..       ...    ...       ...     ...   
824      824    886         0       2   
825      825    887         1       1   
826      826    888         0       3   
827      827    889         1       1   
828      828    890         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
824                              Montvila, Rev. Juozas    male  27.0      0   
825                       Graham, Miss. Margaret Edith  female  19.0      0   
826           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
827                              Behr, Mr. Karl Howell    male  26.0      0   
828                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
824      0            211536  13.0000   NaN        S  
825      0            112053  30.0000   B42        S  
826      2        W./C. 6607  23.4500   NaN        S  
827      0            111369  30.0000  C148        C  
828      0            370376   7.7500   NaN        Q  

[829 rows x 13 columns]

## Looping through a DataFrame

In [100]:
for idx,row in my_dataset.iterrows():
    if row['PassengerId'] == 1:
        row["Pclass"] = 2 # some random statement to set a specific value 
    break

In [99]:
row

PassengerId                          1
Survived                             0
Pclass                               2
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object